# Generated by Django 2.2.1 on 2019-06-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
